name: coronatracker
description: Track the outbreak of the corona virus.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  flutter_svg: any
  provider: any
  flutter_bloc: any
  intl: any
  google_nav_bar: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/background_art_1.svg
    - assets/svgs/background_art_2.svg
    - assets/svgs/doctor_1.svg
    - assets/svgs/doctor_2.svg
    - assets/svgs/map.svg
    - assets/images/caugh.png
    - assets/images/fever.png
    - assets/images/headache.png
    - assets/images/map.png
    - assets/images/own_test.png
    - assets/images/virus.png
    - assets/images/wash_hands.png
    - assets/images/wear_mask.png
    - assets/images/dress.png
    - assets/do_dont.png
    - assets/gifs/home_page.gif
    - assets/gifs/light_1.gif
    - assets/gifs/light_2.gif
    - assets/gifs/dark_1.gif
    - assets/gifs/dark_2.gif
    - assets/gifs/loading_light.gif
    - assets/gifs/loading_dark.gif